CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT,
    name TEXT NOT NULL,
    google_id TEXT UNIQUE,
    email_notifications BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rooms (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    capacity INTEGER NOT NULL,
    hourly_rate DOUBLE PRECISION NOT NULL DEFAULT 35.00,
    peak_hour_rate DOUBLE PRECISION NOT NULL DEFAULT 50.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reservations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id INTEGER NOT NULL,
    user_id INTEGER,
    date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    contact_name TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    contact_email TEXT,
    num_people INTEGER NOT NULL,
    language TEXT DEFAULT 'en',
    status TEXT CHECK(status IN ('confirmed', 'cancelled', 'completed', 'no_show', 'pending', 'rejected')) DEFAULT 'confirmed',
    total_cost DOUBLE PRECISION NOT NULL,
    deposit_paid DOUBLE PRECISION DEFAULT 0.00,
    cancellation_token TEXT UNIQUE DEFAULT NULL,
    requested_at TIMESTAMP DEFAULT NULL,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (room_id) REFERENCES rooms(id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CHECK (num_people > 0),
    CHECK (start_time >= '11:00' AND (end_time <= '25:00' OR end_time <= '01:00'))
);

INSERT INTO rooms (id, name, capacity, hourly_rate, peak_hour_rate)
SELECT 1, 'Room 1', 8, 35.00, 50.00
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE id = 1);

INSERT INTO rooms (id, name, capacity, hourly_rate, peak_hour_rate)
SELECT 2, 'Room 2', 8, 35.00, 50.00
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE id = 2);

INSERT INTO rooms (id, name, capacity, hourly_rate, peak_hour_rate)
SELECT 3, 'Room 3', 8, 35.00, 50.00
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE id = 3);

SELECT setval(pg_get_serial_sequence('rooms', 'id'), GREATEST((SELECT MAX(id) FROM rooms), 1), true);

CREATE TABLE IF NOT EXISTS idle_reservations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id INTEGER NOT NULL,
    date TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (reservation_id) REFERENCES reservations(id)
);

CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    role TEXT NOT NULL,
    path TEXT,
    method TEXT,
    request_id TEXT,
    details TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reservation_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id INTEGER NOT NULL,
    action TEXT NOT NULL,
    snapshot TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (reservation_id) REFERENCES reservations(id)
);

CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    reservation_id INTEGER,
    message TEXT NOT NULL,
    read INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_reservations_room_date ON reservations(room_id, date);
CREATE INDEX IF NOT EXISTS idx_reservations_date_status ON reservations(date, status);
CREATE INDEX IF NOT EXISTS idx_idle_reservations_date_res ON idle_reservations(date, reservation_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_action_time ON audit_log(action, created_at);
CREATE INDEX IF NOT EXISTS idx_reservation_history_res ON reservation_history(reservation_id, created_at);

CREATE TABLE IF NOT EXISTS direct_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    session_id VARCHAR(255) NOT NULL,
    guest_name VARCHAR(255),
    guest_email VARCHAR(255),
    message TEXT NOT NULL,
    sender_role VARCHAR(50) NOT NULL CHECK(sender_role IN ('customer', 'staff', 'guest')),
    read_by_staff INTEGER DEFAULT 0,
    read_by_user INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_direct_messages_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_direct_messages_session ON direct_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_direct_messages_user ON direct_messages(user_id);
